### ISSUE TITLE
Tích hợp thêm tính năng hỗ trợ tạo mã momo pay đa năng

### ISSUE THREAD

**Issue by nguyenthao1988** [xuannghia/vietnam-qr-pay#3]
Chào bạn, bạn có thể tích hợp thêm api chức năng tạo mã qr momo đa năng.

**Comment by xuannghia** [comment]
Cám ơn bạn đã góp ý, mình sẽ tìm hiểu và hỗ trợ API tạo nhanh mã QR đa năng của Momo & ZaloPay sớm nhất có thể nhé

**Comment by xuannghia** [comment]
Mình có thêm 1 ví dụ cho việc tạo mã QR Momo, bạn xem thử [tại đây](https://github.com/xuannghia/vietnam-qr-pay?tab=readme-ov-file#qr-%C4%91a-n%C4%83ng-c%E1%BB%A7a-momo-v%C3%A0-zalopay) nhé

**Comment by nguyenthao1988** [comment]
Cảm ơn bạn nhiều nhé
